# Generated by Django 5.1.1 on 2024-10-15 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='mall',
            name='name',
            field=models.CharField(default='Unknown Mall', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
