# Generated by Django 5.1.1 on 2024-10-03 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_location_city_alter_movie_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown Provider', max_length=100)),
                ('external_eatables_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='timings',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AddField(
            model_name='city',
            name='pin_code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(default='Unknown Actors', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown Director', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(default='Unknown Producer', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default='Untitled Movie', max_length=200),
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.city')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_multiplex', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.city')),
                ('mall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.mall')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Screen 1', max_length=100)),
                ('display_name', models.CharField(default='Standard Screen', max_length=100)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(default='12:00:00')),
                ('end_time', models.TimeField(default='14:00:00')),
                ('interval_time', models.TimeField(blank=True, null=True)),
                ('interval_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.screen')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
