# Generated by Django 5.1.1 on 2024-10-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_mall_name_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
